name: bensnexus
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7

  # Utilitaires
  image_picker: ^1.1.2
  pinput: ^5.0.1
  http: ^1.2.1
  
  # Géolocalisation
  geolocator: ^12.0.0
  google_maps_flutter: ^2.7.0 # Ajout pour la carte
  permission_handler: ^12.0.1
  
  # Enregistrement audio
  record: ^5.2.1
  path_provider: ^2.1.5

  #ajout de prince
  font_awesome_flutter: ^10.8.0
  flutter_svg: ^2.2.0
  intl_phone_field: ^3.2.0
  shared_preferences: ^2.5.3
  loading_animation_widget: ^1.3.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # J'ai également ré-ajouté votre dossier d'icônes personnalisées
  assets:
    - assetes/image/